version: '3'

services:
  minecraft:
    image: minecraft:latest
    container_name: minecraft
    ports:
      - "25565:25565"
    volumes:
      #- ./mods:/opt/mods
      - ./data:/opt/data
      - ./config:/opt/config
# volumes:
#   db: {}