name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build Vanilla image
      run: ./gradlew buildAllVanilla
    - name: Build Forge image
      run: ./gradlew buildAllForge
    - name: Push Vanilla image
      env:
        DOCKER_USERNAME: ${{ secrets.dockerUsername }}
        DOCKER_TOKEN: ${{ secrets.dockerToken }}
      run: ./gradlew pushAllVanilla
    - name: Push Forge image
      env:
        DOCKER_USERNAME: ${{ secrets.dockerUsername }}
        DOCKER_TOKEN: ${{ secrets.dockerToken }}
      run: ./gradlew pushAllForge